services:
  silhouette-app:
    build:
      context: packages/silhouette-2d
      args:
        APP_PORT: ${APP_PORT:-3000}
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    volumes:
      - ./data/output:/app/data:ro
